#!/bin/bash
# ====================================================
# send-dpkglog-upgrade - Permette di analizzare i log con
# gli aggiornamenti settimanali e invia una email 
# riassuntiva alla maling list
# ====================================================
# @authors: Massimo Barbieri (massimo@fsfe.org)
#	    Alessandro Alboni (alle@inventati.org)
#           (Add your name if you contribute)
# ====================================================
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU GENERAL PUBLIC LICENSE
# License as published by the Free Software Foundation; either 
# version 3 of the License, or any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
#  
# You should have received a copy of the GNU Lesser General Public 
# License along with this library.  If not, see <http://www.gnu.org/licenses/>.
###########################################################################


DESTINATARIO="hackers@XXXXXXXX" #Correggere indirizzo prima di eseguire
OGGETTO="Riepilogo aggiornamenti del `date +%d\ %b\ %Y`"
EMAILMESSAGE="/tmp/emailmessage.txt"

#TODO: in teoria questa riga si può eliminare poiché il file viene riscritto
# ad ogni esecuzione
rm -rf $EMAILMESSAGE

#TODO: Aggiungere un preambolo per far capire alla lista cos'è 
# il messaggio che stanno ricevendo

cat /var/log/dpkg.* |grep 'install\|upgrade' | grep "$(date +%Y-%m-%d)\|$(date +%Y-%m-%d -d '1 day ago')\|$(date +%Y-%m-%d -d '2 day ago')\|$(date +%Y-%m-%d -d '3 day ago')\|$(date +%Y-%m-%d -d '4 day ago')\|$(date +%Y-%m-%d -d '5 day ago')\|$(date +%Y-%m-%d -d '6 day ago')" | grep -v status | grep -v trigproc | uniq > $EMAILMESSAGE

mail -s "$OGGETTO" "$DESTINATARIO" < $EMAILMESSAGE
